dalance/svlint

Cargo.lock
Cargo.toml
src/main.rs

As discussed in #8, the filelist parser has been made into its own crate. The crate is [verilog-filelist-parser](https://crates.io/crates/verilog-filelist-parser)

Update to new verilog filelist parser crate

---

src/rules/function_with_automatic.rs
src/rules/priority_keyword.rs
src/rules/unique0_keyword.rs
src/rules/unique_keyword.rs

Fixed typo
`simulaton ` -> `simulation`

Fixed typo

---

src/printer.rs

Solves panicking when rule default_nettype_none fails on a file with empty first line.  
Would prefer that the rule just pointed to the first non-empty line, as I believe it would help understanding the error better than empty space.

Fixes dalance/svlint#94 - Add handling of empty first line

---

RULES.md
src/rules/localparam_explicit_type.rs
src/rules/localparam_type_twostate.rs
src/rules/parameter_explicit_type.rs
src/rules/parameter_type_twostate.rs
testcases/fail/localparam_explicit_type.sv
testcases/fail/localparam_type_twostate.sv
testcases/fail/parameter_explicit_type.sv
testcases/fail/parameter_type_twostate.sv
testcases/pass/localparam_explicit_type.sv
testcases/pass/localparam_type_twostate.sv
testcases/pass/parameter_explicit_type.sv
testcases/pass/parameter_type_twostate.sv

- `(localparam|parameter)_explicit_type` Ensures that types are specified to clarify intent.
- `(localparam|parameter)_type_twostate` Ensures that parameters are twostate.

New rules for parameter/localparam types.

---

RULES.md
src/rules/sequential_block_in_always_comb.rs
src/rules/sequential_block_in_always_ff.rs
src/rules/sequential_block_in_always_latch.rs
testcases/fail/sequential_block_in_always_comb.sv
testcases/fail/sequential_block_in_always_ff.sv
testcases/fail/sequential_block_in_always_latch.sv
testcases/pass/sequential_block_in_always_comb.sv
testcases/pass/sequential_block_in_always_ff.sv
testcases/pass/sequential_block_in_always_latch.sv

These rules are useful to prevent unwittingly introducing sequential dependencies, which would mismatch synthesis. E.g.
```
always_comb begin
a = expensive_function(y); // Woops! Computed on update of z.
b = z;
end
```
Another effect of these rules is that flops become easier to audit. E.g. this sort of thing is prevented:
```
always_ff @ (posedge clk)
if (rst) begin
a <= 0;
// Woops! Forgot to reset b.
end else begin
a <= z;
b <= y;
end
```

New rules to forbid begin/end within always_* constructs.

---

src/main.rs

Change `from_iter` (deprecated) to `parse_from`.
<https://docs.rs/clap/latest/src/clap/derive.rs.html#101-118>
<https://docs.rs/clap/latest/src/clap/derive.rs.html#195-206>

Fix warnings on `cargo test`.

---

README.md
src/main.rs

Look for special envvar SVLINT_CONFIG.
If SVLINT_CONFIG is not set (as currently), then hierarchical search (no change).
If SVLINT_CONFIG is set but is invalid, then hierarchical search (no change).
If SVLINT_CONFIG is set AND --config is given, then use SVLINT_CONFIG.
Enables use with standardised environments like GNU Modulefiles.
E.g. `$ module load svlint` would append to PATH and set SVLINT_CONFIG.
Or, more realistically, `$ module load projectFoo` would set environment
variables for all the project's tools (where svlint is one of many).
Different projects can then have different rule-sets, and everybody working
on the same project uses the same rule-set.
There's a partner PR at https://github.com/dalance/svls/pull/120

Take configuration file from environment variable.

---

src/main.rs

Based on <https://github.com/Raamakrishnan/verilog-filelist-parser/pull/2>.
@Raamakrishnan This is indeed a better place for such a debug-aid.
Exposed and fixed bug where first character was dropped from define strings.
E.g. In a filelist, `+define+FOO=bar` was resulting in a define with identifer `FOO` (correct) and a value `ar` (incorrect).
Each filelist is printed in YAML format (because it's easy and no dependencies).
As filelists can override each other's defines, the final result is printed with `.` as the filename.

New flag `--dump-filelist` to help debug filelist issues.

---

src/main.rs

We are using svlint to read filelists and currently the message `Config file is not found. Enable all rules` may/may not be output, depending on whether the file exists in the workspace or if `$SVLINT_CONFIG` is set. This is to add predictable output.
This would also allow dalance/svls-vscode#9 to be implemented, via a setting that adds `--silent` to the command.

Silent flag silences .toml not found message

---

src/main.rs

Add `-E` flag for preprocessor-only behaviour.
- Same flag as GCC, Clang, Verilator, Icarus, etc.
- Parsing (and linting) is not performed with this flag.
- Useful to see exactly what `parse_sv()` is operating on.
- Useful for debugging checks around compiler directives.
- Useful to have (yet another) SV preprocessor tool.

Print preprocessor output to STDOUT with `-E`.

---

src/rules/style_keyword_1space.rs
src/rules/style_keyword_construct.rs

Allow indented assignment to with concatenation on LHS.
This code structure is useful for tying off lots of wires:
```systemverilog
assign
{ foo
, bar
, baz[i][j][k]
} = '0
```
The equivalent using `always_comb` is already allowed. All code which passed before this commit, still passes.

Relax style rule on assign keyword.

---

RULES.md
src/rules/explicit_case_default.rs
src/rules/explicit_if_else.rs
testcases/fail/explicit_case_default.sv
testcases/fail/explicit_if_else.sv
testcases/pass/explicit_case_default.sv
testcases/pass/explicit_if_else.sv

@supleed2 Thanks for finding #182 and the testcases.
The problem was using `unwrap_node!()` which only returns the first instance.
This PR uses a 1b FSM which is set whenever an AlwaysConstruct is entered, and cleared on exit.

Bugfix #182 explicit_if_else, explicit_case_default

---

RULES.md
md/explanation-action_block_with_side_effect.md
src/rules/action_block_with_side_effect.rs
testcases/fail/action_block_with_side_effect.sv
testcases/pass/action_block_with_side_effect.sv

As per #181.
Detect non-sensical cases like this:
```systemverilog
assert (foo) begin: pass_action_block
$display("IO says it passed"); // Usually replace with $info.
end: pass_action_block
else begin: fail_action_block
$display("IO says it failed"); // Usually replace with $error, or perhaps $fatal, $warning, $info.
a++; // Undefined behaviour...
b--; // ...but will probably work in single-threaded sim.
end: fail_action_block
```

New Rule: `action_block_with_side_effect`

---

Cargo.toml
src/main.rs
src/printer.rs

- Depends on corresponding PR in sv-parser: https://github.com/dalance/sv-parser/pull/69
- Rename `main.rs`'s `print_parse_error()` -> `print_parser_error()` to avoid confusion with function of the same name in `printer.rs`.
- New function `print_preprocess_error` is essentially the same as `print_parse_error` but allows users to distinguish pp parse errors.
- Bump sv-parser from 0.12.1 to 0.12.2.

Distinguish between parse/preprocess errors. Bump sv-parser.

---

src/main.rs
src/printer.rs
testcases/expected/dump_filelist_1
testcases/expected/dump_filelist_2
testcases/expected/dump_filelist_3
testcases/expected/dump_filelist_4
testcases/expected/dump_filelist_5
testcases/resources/child1.fl
testcases/resources/child2.fl
testcases/resources/grandparent1.fl
testcases/resources/parent1.fl

- Bug1: Output should be repeatable. Before this PR, defines were printed in random order.
- Bug2: Before this PR, `--dump-filelist` only printed the list of files if `--filelist` was also given.
After this PR, the behavior is consistent between `svlint -f foo.f` and `svlint foo.sv`, i.e. the list
of files being processed (and defines, incdirs) is printed without any SV parsing.
- Improvement: All printed output is now goes via `Printer`, instead of mix of `print`, `println`,
`write`, and `Printer`.
Support has been added to capture the output and use this in unittests.
- There are now 5 unittests for `--dump-filelist`.
- I intend to open future PRs with unittest for other flags.

Bugfix/Improvement: Unittests for `--dump-filelist`, and fix two bugs.

---

src/rules/style_keyword_0or1space.rs
src/rules/style_keyword_0space.rs
src/rules/style_keyword_1or2space.rs
src/rules/style_keyword_1space.rs
src/rules/style_keyword_construct.rs
src/rules/style_keyword_datatype.rs
src/rules/style_keyword_end.rs
src/rules/style_keyword_maybelabel.rs
src/rules/style_keyword_newline.rs

- Reported in #211.
- New regex determined by looking at all the possibilities in sv-parser, instead of reading the LRM.
- Previous regex did not allow for characters $, ', B, X, or Z.
- I think only $ was causing a real issue, but keyword regex has been updated to include all characters to avoid confusing corner-cases later.

Bugfix: Correct keyword regex used by `style_keyword_*`.

---

.github/workflows/mdgen.yml
Cargo.toml
RULES.md
src/mdgen.rs

- Use the `default-run` manifest key to allow `cargo run` (instead of `cargo run --bin=svlint`) which is a little easier for development.
- Write directly to `RULES.md` with `cargo run --bin=mdgen` (instead of `cargo run --bin=mdgen > RULES.md`).
- Allow command to be run from anywhere in the repo, and slightly less typing.
- This allows future work to write multiple files instead of only `RULES.md` (intended for future PR based on [rulesets-dev](https://github.com/DaveMcEwan/svlint/tree/rulesets-dev))
- Update workflow file for mdgen:
- `actions/checkout@v1` -> `actions/checkout@v3`
- `EndBug/add-and-commit@v2.1.0` -> `EndBug/add-and-commit@v9`

Improvement: Update mdgen and its workflow.

---

RULES.md
src/mdgen.rs

In `RULES.md`, split the "Pass/Fail Example" code blocks into their respective testcases.
Examples are split the same way as in `build.rs` for the unittests, i.e. on lines with 80 consecutive `/`.
Apologies if this is too minor! This was developed on my rulesets-dev branch, but it isn't specific to that work.

Improvement: Split testcase examples in documentation.

---

Cargo.toml
src/main.rs
src/rules/re_forbidden_assert.rs
src/rules/re_required_assert.rs

- Update sv-parser to 0.12.3
- Add support for `Error::ReadUtf8`.
- Rename `Assetion` -> `Assertion` (see https://github.com/dalance/sv-parser/pull/73).
- Add argument showing macro name for `DefineNoArgs`.
- Clarify wording of messages from `DefineNoArgs`, `DefineArgNotFound`, and `DefineNotFound`.
- Addresses comment about better UTF-8 error handling on #224.

Improvement: Nicer error message on file of invalid UTF-8.

---

Cargo.toml
src/main.rs
src/printer.rs
testcases/expected/dump_filelist_6
testcases/expected/dump_filelist_7
testcases/expected/dump_filelist_8

- Update sv-parser to v0.13.0, avoiding yanked v0.12.3
- Update clap from v3.1.18 to v3.2.* (currently v3.2.23) which is the minimum version to get ValueEnum.
The authors of clap appear to have stopped releasing multiple versions per day for `v3.x`!
- Change `--dump-filelist` from bool to ValueEnum.
- Previous behavior of not using the flag is equivalent to `--dump-filelist=no`, or just not using
the flag (backwards compatible).
- Previous behavior of using the flag is equivalent to `--dump-filelist=yaml`.
That's a breaking change to the flag.
The output is functionally equivalent (except for the removed control codes).
- Possible values `files`, `incdirs`, `defines` give new modes where output is intended to be
processed by shell scripts (see #224).
One line per file/incdir/define, …

Improvement: Don't emit control codes to STDOUT for non-colored output.

---

MANUAL.md
md/explanation-style_keyword_0or1space.md
md/explanation-style_keyword_0space.md
md/explanation-style_keyword_1or2space.md
md/explanation-style_keyword_1space.md
md/explanation-style_keyword_construct.md
md/explanation-style_keyword_datatype.md
md/explanation-style_keyword_end.md
md/explanation-style_keyword_maybelabel.md
md/explanation-style_keyword_new.md
md/ruleset-style.md
rulesets/style.toml
src/linter.rs
src/rules/default_nettype_none.rs
src/rules/explicit_case_default.rs
src/rules/prefix_inout.rs
src/rules/prefix_input.rs
src/rules/prefix_instance.rs
src/rules/prefix_interface.rs
src/rules/prefix_module.rs
src/rules/prefix_output.rs
src/rules/prefix_package.rs
src/rules/style_keyword_new.rs
testcases/fail/style_keyword_new.sv
testcases/pass/default_nettype_none.sv
testcases/pass/style_keyword_new.sv

- #210 Alternate implementation of `default_nettype_none` which allows control comments to work such that the rule can be enabled/disabled for files with multiple modules.
- Allows straightforward extension to support `` `resetall ``, but I'm unsure if that should be a different rule. 
- #225 Apply `prefix_package` and `prefix_interface` only to declarations, not everywhere that a package/interface identifier can be used.
- Includes a minor tidy of the `prefix_*` rules to use a utility function `linter::check_prefix()`.
- #235 Create a new rule `style_keyword_new` and remove the `new` keyword from `style_keyword_0space`.
- Includes corresponding minor changes to explanations of related rules.
- Includes the corresponding minor change to ruleset-style.

Bugfix: Addresses #210, #225, #235.

---

src/linter.rs

This fixes a bug where svlint would panic when checking if the plugin rule is enabled or not.

Bugfix: insert plugins in enabled hashmap during load

---

src/linter.rs
src/main.rs

- Change `linter.load()` to expect `Vec<Rule>` instead of `SyntaxRule`.
This allows plugins to contain multiple rules of either `SyntaxRule` or `TextRule`.
- Provide a macro `pluginrules` to simplify `get_plugin`.
- Superceeds #251, Thanks @skjdbg :)
- Two plugin-related usability changes:
1. Throw an error when a plugin can't be loaded, rather than silently ignoring it.
2. When no `.svlint.toml` is found but `--plugin` is given, don't enable all rules.
- As per #253, this is intended to be merged before v0.8.0 is released.
- Fixes #256.

Feature: Update plugin API.

---

src/linter.rs
src/main.rs
src/textrules/header_copyright.rs
src/textrules/style_directives.rs
src/textrules/style_semicolon.rs
src/textrules/style_textwidth.rs

- Change/break the API (again, sorry) for textrules.
After discussion on #257, @skjdbg and I think this is a more flexible solution.
- This change is called Option1 in #257.
- Instead of passing each line as `&str`, pass as `Option<&str>`.
Rules should interpret `Some(x)` as a line of text, and `None` as a signal that a new item from the list of files is about to be processed.
This allows textrules to reset (or otherwise update) any internal state machines.
- Found when passing multiple files like `svlint foo.sv bar.sv`, and the textrule `header_copyright` doesn't reset its line counter.
This change resets the counter before each file is processed.
- This doesn't *require* <https://github.com/dalance/svls/pull/216> to be updated because its `Cargo.toml` is pinned to svlint v0.8.0, but if …

Bugfix: Change textrules API to pass `line: Option<&str>`.

---

Cargo.toml
rulesets/svlint-DaveMcEwan-design
rulesets/svlint-DaveMcEwan-designnaming
rulesets/svlint-designintent
rulesets/svlint-parseonly
rulesets/svlint-simsynth
rulesets/svlint-style
rulesets/svlint-verifintent
src/main.rs
src/mdgen.rs
src/printer.rs

- Rename options to make the whole interface consistent and intuitive for new users.
- `--example` -> `--config-example`
- `--update` -> `--config-update`
- Backwards compatibility maintained with aliases.
- Rename options to be consistent with other tools (GCC, Clang, Verilator, etc.).
- `-i/--include` -> `-I/incdir` (also consistent with filelist plusarg/keyword)
- `-d` -> `-D`
- Backwards compatibility maintained with aliases.
- Remove unnecessary choice `--dump-filelist=no`.
Technically a breaking change, but I doubt it is ever used in practice.
- Add long format for every option.
- `-E` + `--preprocess-only`
- `-1` + `--oneline` (consistent with Git)
- Add new option `--shell-completion` to print shell completion scripts to STDOUT.
- Fixes #245 which requested this feature.
- Based …

Improvement: Cleanup the command-line interface.

---

rulesets/svls-DaveMcEwan-design
rulesets/svls-DaveMcEwan-design.cmd
rulesets/svls-DaveMcEwan-designnaming
rulesets/svls-DaveMcEwan-designnaming.cmd
rulesets/svls-designintent
rulesets/svls-designintent.cmd
rulesets/svls-parseonly
rulesets/svls-parseonly.cmd
rulesets/svls-simsynth
rulesets/svls-simsynth.cmd
rulesets/svls-style
rulesets/svls-style.cmd
rulesets/svls-verifintent
rulesets/svls-verifintent.cmd
src/mdgen.rs

These are usable in Vim with vim-lsp like this:
```vim
if executable('svls-parseonly')
au User lsp_setup call lsp#register_server({
\ 'name': 'svls-parseonly',
\ 'cmd': {server_info->['svls-parseonly']},
\ 'whitelist': ['systemverilog'],
\ })
endif
```
Users can configure their editor to use different commands via editor-specific interfaces like key-bindings, drop-down menus, etc.

Feature: Provide wrapper scripts for svls, in addition to svlint.

---

.github/workflows/release.yml
Makefile
README.md

Makes it easier to use rulesets for non-dev users that don't/won't clone the repo.
Before this PR, a release ZIP looked like:
```
svlint-v0.8.0-x86_64-lnx.zip
├── svlint                        <- The binary executable
└── svlint_MANUAL_v0.8.0.pdf      <- The documentation
```
With this PR, a release ZIP looks like:
```
svlint-v0.8.0-x86_64-lnx.zip
├── bin
│   ├── svlint                    <- The binary executable
│   ├── parseonly.toml            
│   ├── ... *.toml                <- TOML configurations
│   ├── svlint-parseonly
│   └── ... svlint-*              <- Wrapper scripts
└── doc
└── svlint_MANUAL_v0.8.0.pdf  <- The documentation
```
Example ZIPs are here: <https://github.com/DaveMcEwan/svlint/releases/tag/v0.0.12-DONOTUSE>

Improvement: Bundle rulesets in release ZIP files.

---

CONTRIBUTING.md
MANUAL.md
md/ruleset-style.md
md/syntaxrules-explanation-style_operator_arithmetic.md
md/syntaxrules-explanation-style_operator_arithmetic_leading_space.md
md/syntaxrules-explanation-style_operator_boolean_leading_space.md
md/syntaxrules-explanation-style_operator_integer.md
md/syntaxrules-explanation-style_operator_integer_leading_space.md
rulesets/style.toml
src/syntaxrules/style_operator_arithmetic_leading_space.rs
src/syntaxrules/style_operator_boolean_leading_space.rs
src/syntaxrules/style_operator_integer_leading_space.rs
testcases/syntaxrules/fail/style_operator_arithmetic_leading_space.sv
testcases/syntaxrules/fail/style_operator_boolean_leading_space.sv
testcases/syntaxrules/fail/style_operator_integer_leading_space.sv
testcases/syntaxrules/pass/style_operator_arithmetic_leading_space.sv
testcases/syntaxrules/pass/style_operator_boolean_leading_space.sv
testcases/syntaxrules/pass/style_operator_integer_leading_space.sv

Hi, @dalance!
I added some new rules for **leading spaces** of binary operators.
The names of the new rules are the following:
- `style_operator_arithmetic_leading_space`
- `style_operator_boolean_leading_space`
- `style_operator_integer_leading_space`
Each of these rules corresponds to the following existing rules.
- `style_operator_arithmetic`
- `style_operator_boolean`
- `style_operator_integer`
These existing rules are for the number of following spaces and do not support leading spaces.
For example:
When I give the following SystemVerilog code to the linter with `style_operator_arithmetic` rule enabled, 
```sv
module M;
localparam int P2 = a  + b; // Multiple spaces before `+`.
// No space before `*`.
localparam int P3 = a* b;
endmodule
```
I expect the result that says the numbers …

New rules for leading spaces of binary operators

---

MANUAL.md
md/manual-introduction.md
src/main.rs

As per #269, thanks @Sv3n.
- 3 new environment variables `SVLINT_INCDIRS`, `SVLINT_PREFILES`, and `SVLINT_POSTFILES` to facilitate always-used files, such as a UVM installation.
- The environment variables are each a colon-separated list of locations on the filesystem, just like `PATH`, so this mechanism is compatible with Environment Modules.
- This is effectively a shortcut to avoid lots of typing on the command line, so you can use the `--dump-filelist` option to see exactly what is being passed to the parser.
- In the same way that `svlint -Ifoo/ bar.sv` only looks for `bar.sv` in the current directory, but not in the incdir `foo/`, the files listed in `SVLINT_PREFILES` and `SVLIST_POSTFILES` are not searched for in any include directories.
- Minor changes to introduction section of …

Feature: Include files and incdirs from the environment.

---

MANUAL.md
md/syntaxrules-explanation-package_item_not_in_package.md
src/syntaxrules/package_item_not_in_package.rs
testcases/syntaxrules/fail/package_item_not_in_package.sv
testcases/syntaxrules/pass/package_item_not_in_package.sv

As per #209.
- Original reported in https://github.com/dalance/sv-parser/issues/68

New rule: `package_item_not_in_package`

---

.gitignore
CONTRIBUTING.md
MANUAL.md
build.rs
md/syntaxrules-explanation-interface_identifier_matches_filename.md
md/syntaxrules-explanation-module_identifier_matches_filename.md
md/syntaxrules-explanation-package_identifier_matches_filename.md
md/syntaxrules-explanation-program_identifier_matches_filename.md
src/syntaxrules/interface_identifier_matches_filename.rs
src/syntaxrules/module_identifier_matches_filename.rs
src/syntaxrules/package_identifier_matches_filename.rs
src/syntaxrules/program_identifier_matches_filename.rs
testcases/syntaxrules/fail/interface_identifier_matches_filename.sv
testcases/syntaxrules/fail/module_identifier_matches_filename.sv
testcases/syntaxrules/fail/package_identifier_matches_filename.sv
testcases/syntaxrules/fail/program_identifier_matches_filename.sv
testcases/syntaxrules/pass/interface_identifier_matches_filename.sv
testcases/syntaxrules/pass/module_identifier_matches_filename.sv
testcases/syntaxrules/pass/package_identifier_matches_filename.sv
testcases/syntaxrules/pass/program_identifier_matches_filename.sv

Closes dalance/svlint#252
The pass testcase is slightly unintuitive in that the module name does not actually match the file it's currently in, but works due to how build.rs modifies the filenames for testing.

New rule that ensures module/interface/package/program identifier matches the filename it's in

---

MANUAL.md
md/syntaxrules-explanation-implicit_case_default.md
src/syntaxrules/implicit_case_default.rs
testcases/syntaxrules/fail/implicit_case_default.sv
testcases/syntaxrules/pass/implicit_case_default.sv

This pull request is a simple case implementation for implicit case default. It keeps track of implicitly defined variables in a vector and references it when it encounters it under the case statement. Passes if there is a default case defined.
- closes dalance/svlint#268

New Rule: Implicit case default

---

CONTRIBUTING.md
Cargo.toml
src/main.rs

- Add chardetng and encoding_rs dependencies in Cargo.toml to detect and decode non-UTF-8 files.
- Update file reading logic in main.rs to read bytes, detect encoding, and decode file contents.
- Introduce lint_gbk_encoded_verilog test case to verify processing of GBK-encoded Verilog files.

feat: add support for file encoding detection

---

MANUAL.md
md/syntaxrules-explanation-explicit_brackets_for_confusing_precedence.md
src/syntaxrules/explicit_brackets_for_confusing_precedence.rs
testcases/syntaxrules/fail/explicit_brackets_for_confusing_precedence.sv
testcases/syntaxrules/pass/explicit_brackets_for_confusing_precedence.sv

This corresponds to similar warnings that GCC/Clang will give you (with -Wall) for mixing comparison and bitwise operators without brackets (because C has the same error-prone operator precedence).
Fixes #299

Add rule to prevent mixing operators with confusing precedence

---

src/main.rs

Always print a message for passing and failing files, and also use `.display()` instead of `.to_string_lossy()`.

Improve verbose pass/fail message

---

CONTRIBUTING.md
MANUAL.md
md/ruleset-style.md
md/syntaxrules-explanation-style_keyword_0or1space.md
md/syntaxrules-explanation-style_keyword_0space.md
md/syntaxrules-explanation-style_keyword_1or2space.md
md/syntaxrules-explanation-style_keyword_1space.md
md/syntaxrules-explanation-style_keyword_1spaceornewline.md
md/syntaxrules-explanation-style_keyword_construct.md
md/syntaxrules-explanation-style_keyword_datatype.md
md/syntaxrules-explanation-style_keyword_end.md
md/syntaxrules-explanation-style_keyword_maybelabel.md
md/syntaxrules-explanation-style_keyword_new.md
rulesets/style.toml
src/syntaxrules/style_keyword_1space.rs
src/syntaxrules/style_keyword_1spaceornewline.rs
testcases/syntaxrules/fail/style_keyword_1spaceornewline.sv
testcases/syntaxrules/pass/style_keyword_1spaceornewline.sv

Closes #296
As mentioned in the linked issue, the `matches` keyword has two uses. In `if (a matches ...)`, it wants to have exactly one space. In `case (a) matches ...`, it wants a newline (or a space then comment). This PR adds a rule to handle these cases.

feat: add `style_keyword_1spaceornewline` rule
